//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoXamarin {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoXamarin.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adventure.
        /// </summary>
        public static string adventureLabel {
            get {
                return ResourceManager.GetString("adventureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author:.
        /// </summary>
        public static string authorLabel {
            get {
                return ResourceManager.GetString("authorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authors.
        /// </summary>
        public static string authorsTitle {
            get {
                return ResourceManager.GetString("authorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth:.
        /// </summary>
        public static string birthLabel {
            get {
                return ResourceManager.GetString("birthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Books.
        /// </summary>
        public static string booksTitle {
            get {
                return ResourceManager.GetString("booksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comedy.
        /// </summary>
        public static string comedyLabel {
            get {
                return ResourceManager.GetString("comedyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fantasy.
        /// </summary>
        public static string fantasyLabel {
            get {
                return ResourceManager.GetString("fantasyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launched:.
        /// </summary>
        public static string launchedLabel {
            get {
                return ResourceManager.GetString("launchedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Name:.
        /// </summary>
        public static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        public static string namePlaceholder {
            get {
                return ResourceManager.GetString("namePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Author.
        /// </summary>
        public static string newAuthorTitle {
            get {
                return ResourceManager.GetString("newAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Book.
        /// </summary>
        public static string newBookTitle {
            get {
                return ResourceManager.GetString("newBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pages.
        /// </summary>
        public static string pagesLabel {
            get {
                return ResourceManager.GetString("pagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Pages:.
        /// </summary>
        public static string pagesLabelForm {
            get {
                return ResourceManager.GetString("pagesLabelForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paranormal.
        /// </summary>
        public static string paranormalLabel {
            get {
                return ResourceManager.GetString("paranormalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone numer:.
        /// </summary>
        public static string phoneLabel {
            get {
                return ResourceManager.GetString("phoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a phone number.
        /// </summary>
        public static string phonePlaceholder {
            get {
                return ResourceManager.GetString("phonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Romance.
        /// </summary>
        public static string romanceLabel {
            get {
                return ResourceManager.GetString("romanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Science Fiction.
        /// </summary>
        public static string scifiLabel {
            get {
                return ResourceManager.GetString("scifiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Sex:.
        /// </summary>
        public static string sexLabel {
            get {
                return ResourceManager.GetString("sexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Surname:.
        /// </summary>
        public static string surnameLabel {
            get {
                return ResourceManager.GetString("surnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a surname.
        /// </summary>
        public static string surnamePlaceholder {
            get {
                return ResourceManager.GetString("surnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type:.
        /// </summary>
        public static string typeLabel {
            get {
                return ResourceManager.GetString("typeLabel", resourceCulture);
            }
        }
    }
}
